version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_2204Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: WmCloudStreams
  version: 12.1.0
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.kvv_2204.Kvv_2204Project.project_kvv_2204_Kvv_2204Project_swaggerURL.connections:swaggerURL
  packages:
  - name: Kvv_2204Project
    version: "1.0"
  - name: WmCloudStreams
    version: 12.1.0.0.57
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:getUserByName.connectionAlias
  : $connectionAlias
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.poolable
  : "true"
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cr.preemptiveAuthEnabled
  : "true"
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.sockBuffSize
  : "8192"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:getUserByName.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.retryCount
  : "1"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:updateUser.connectionAlias
  : $connectionAlias
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cr.password
  : "{AES}ML0Q0aVy4miEMaboS+UO/A=="
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:createUsersWithListInput.connectionAlias
  : $connectionAlias
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:getOrderById.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.idleTimeout
  : "-1"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:updatePetWithForm.connectionAlias
  : $connectionAlias
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.retryIfRequestSentOk
  : "true"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:deleteOrder.connectionAlias
  : $connectionAlias
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:getInventory.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.reuseAddr
  : "false"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:logoutUser.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.keepAliveInterval
  : "-1"
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.connectTimeout
  : "30000"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:createUsersWithArrayInput.connectionAlias
  : $connectionAlias
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.tcpNoDelay
  : "false"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:createUser.connectionAlias
  : $connectionAlias
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:deleteUser.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.timeoutType
  : none
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:createUsersWithListInput.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cr.authSchemeType
  : basic
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:placeOrder.virtualServiceName
  : WmCloudStreams.RestVS
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:logoutUser.connectionAlias
  : $connectionAlias
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.poolIncrementSize
  : "1"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:updatePet.connectionAlias
  : $connectionAlias
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cr.username
  : test
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.enableCompression
  : "false"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:getPetById.connectionAlias
  : $connectionAlias
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:deletePet.virtualServiceName
  : WmCloudStreams.RestVS
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:findPetsByStatus.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.startupRetryCount
  : "0"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:findPetsByStatus.connectionAlias
  : $connectionAlias
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:updatePetWithForm.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.readTimeout
  : "30000"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:deleteOrder.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.socketStaleCheck
  : "true"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:addPet.connectionAlias
  : $connectionAlias
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:deletePet.connectionAlias
  : $connectionAlias
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:getOrderById.connectionAlias
  : $connectionAlias
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:updatePet.virtualServiceName
  : WmCloudStreams.RestVS
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:createUser.virtualServiceName
  : WmCloudStreams.RestVS
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:getInventory.connectionAlias
  : $connectionAlias
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.enableSNI
  : "true"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:placeOrder.connectionAlias
  : $connectionAlias
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.minimumPoolSize
  : "1"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:getPetById.virtualServiceName
  : WmCloudStreams.RestVS
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:createUsersWithArrayInput.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.blockTimeout
  : "1000"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:loginUser.connectionAlias
  : $connectionAlias
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.cn.providerUrl
  : https://petstore.swagger.io/v2
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:addPet.virtualServiceName
  : WmCloudStreams.RestVS
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:deleteUser.connectionAlias
  : $connectionAlias
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:loginUser.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..connections:swaggerURL.connectionEnabled
  : "true"
  ? iscloudstreamsconnectorservice.project..kvv_2204..Kvv_2204Project..project_kvv_2204_Kvv_2204Project_swaggerURL..operations..actions:updateUser.virtualServiceName
  : WmCloudStreams.RestVS
